### PR TITLE
Fixed issue #1047

### LINKED ISSUE #1047: Rocq backend import fix
In the new version of mathcomp,
```coq
Require Import mathcomp.ssreflect.ssrbool.
Require Import mathcomp.algebra.ssralg.
Require Import mathcomp.ssreflect.ssrnat.
Require Import mathcomp.ssreflect.eqtype.
Require Import mathcomp.ssreflect.order.
Require Import mathcomp.ssreflect.fintype.
Require Import mathcomp.ssreflect.seq.
Require Import mathcomp.algebra.zmodp.
Require Import mathcomp.reals.reals.
```
Should instead be
```coq
From mathcomp Require Import all_boot.
From mathcomp Require Import all_algebra.
From mathcomp Require Import all_reals.
```
As the current no longer compiles

### PR DESCRIPTION
**Pull request by lstrsrmn**
Fixed issue #1047 by splitting mathcomp imports into the correct format and grouping imports into "all_" notation

Updated tests to expect the new import notation for Rocq

### CODE REVIEW

File: vehicle/src/Vehicle/Backend/Rocq/Compile.hs [hunk 1]
```diff
@@ -38,7 +38,7 @@ import Vehicle.Syntax.Tensor
   )
 
 --------------------------------------------------------------------------------
--- Rocq-specific options
+-- Rocq-specific optionsjuice
```
Comment (MatthewDaggitt) [inline vehicle/src/Vehicle/Backend/Rocq/Compile.hs]: This looks like a typo?

**Review by MatthewDaggitt — CHANGES_REQUESTED** [review]
Otherwise looks great!

Do we need to update some bounds in https://github.com/vehicle-lang/vehicle/blob/dev/vehicle-rocq/vehicle-rocq.opam? If we do, could you also add an entry in the CHANGELOG to make clear that the bounds have changed?

**Review by MatthewDaggitt — APPROVED** [review]
